#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    # Set relative path to shoc executable
    set SHOC='../../../hd/shoc'
endif

echo "Testing 'z' model..."
rm -f in4.nc || true
rm -f out4_z.nc || true

$SHOC -g test4.prm in4.nc

echo "Running, takes ~ 1 minute...."
$SHOC -p test4.prm

echo "DONE"

echo "Testing sigma model..."
rm -f in4.nc || true
rm -f out4_s.nc || true

$SHOC -g test4_s.prm in4.nc

echo "Running, takes ~ 1 minute...."
$SHOC -p test4_s.prm

echo "DONE"

rm -f in4.nc || true
