#!/bin/csh -ef

# Set relative path to shoc executable
set SHOC='../../../hd/shoc'

echo "Testing 'z' model..."
rm -f in1.nc || true
rm -f out1_z.nc || true

$SHOC -g test1.prm in1.nc

$SHOC -p test1.prm

echo "DONE"

echo "Testing sigma model..."
rm -f in1.nc || true
rm -f out1_s.nc || true

$SHOC -g test1_s.prm in1.nc

$SHOC -p test1_s.prm

echo "DONE"

rm -f in1.nc || true
