#!/bin/csh -ef

# Set relative path to shoc executable
set SHOC='../../../hd/shoc'

echo "Testing 'z' model..."
rm -f in2.nc || true
rm -f out2_z.nc || true

$SHOC -g test2.prm in2.nc

$SHOC -p test2.prm

echo "DONE"

echo "Testing sigma model..."
rm -f in2.nc || true
rm -f out2_s.nc || true

$SHOC -g test2_s.prm in2.nc

$SHOC -p test2_s.prm

echo "DONE"

rm -f in2.nc || true
