---
#-------------------------------------------------------------------------------
# Docker development environment composition for ems
# (Not for production use!)
#
# This default compose stack is designed for use on a local development host.
#-------------------------------------------------------------------------------
version: "3.8"

services:
  ems:
    build:
      context: .
      args:
        SHOC: 1
        COMPAS: 1
        EMS_TEST_RUN: 0
    command: "run-ems-tests"
    container_name: ems
    environment:
      EMS_TEST_INCLUDE: '/usr/local/src/ems/model/tests/sediments/test2'
    image: onaci/ereefs-ems-shoc:dev
    volumes:
      - ./model/tests/:/usr/local/src/ems/model/tests/
