#!/bin/csh -ef

# Script to run test

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../../../hd/shoc'
endif

# check shoc
if (! -e $SHOC) then
    echo "cannot find the shoc executable, please build and try again"
    exit(0)
endif

# Ensure output dir is empty
mkdir -p out
rm -rf out/*

# Kick off model
echo "Starting model ..."
$SHOC -p basic.prm

if ($status) then
    echo ".... uh oh!"
else
    echo "... done!"
    echo " "
    echo "Run out.m in Matlab to see results"
endif
