#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    # Set relative path to shoc executable
    set SHOC='../../../hd/shoc'
endif

echo "Testing 'z' model..."
rm -f in7.nc || true
rm -f out7_z.nc || true
rm -f out_pt.nc || true
#rm -f *.eps || true

$SHOC -g test7_diag.prm in7.nc

echo "Running, takes ~ 3 minutes...."
$SHOC -p test7.prm

echo "Running diagnostic test, takes ~ 2 minutes...."
rm -f out7_d.nc || true
rm -f out_pt.nc || true
$SHOC -p test7_diag.prm
mv totals.ts totals_diag.ts

echo "Running explicit mapping test, takes ~ 2 minutes...."
rm -f in7.nc || true
rm -f out7_e.nc || true
$SHOC -g test7_em.prm in7.nc
$SHOC -p test7_em.prm

echo "Running grid refinement test, takes ~ 3 minutes...."
rm -f in7.nc || true
rm -f out7_r.nc || true
$SHOC -g test7_zoom.prm in7.nc
$SHOC -p test7_zoom.prm

echo "Running sigma model test, takes ~ 3 minutes...."
rm -f in7.nc || true
rm -f out7_s.nc || true
$SHOC -g test7_s.prm in7.nc
$SHOC -p test7_s.prm

echo "Running sediment test, takes ~ 3 minutes...."
rm -f in7.nc || true
rm -f out7_sed.nc || true
$SHOC -g test7_sed.prm in7.nc
$SHOC -p test7_sed.prm

echo "Running multiple window test, takes ~ 6 minutes...."
rm -f in7.nc || true
rm -f out7_1w.nc || true
rm -f out7_4w.nc || true
$SHOC -g test7_1w.prm in7.nc
$SHOC -p test7_1w.prm
$SHOC -p test7_4w.prm

echo "DONE"

rm -f in7.nc || true
