#!/bin/bash
#
# Top-level script to run hd tests
#

# Build list of test directories
TESTDIRS=(`ls -d test*`)
LEN=${#TESTDIRS[@]}

ARG=""
if [ $# -gt 0 ]; then
    ARG=$1
fi

SHOC=../../hd/shoc
if [ ! -f $SHOC ];then
    echo "SHOC executable ($SHOC) not found, skipping ...."
    exit -1
fi

echo "------------------------"
echo "Found ${LEN} tests in hd"
echo "------------------------"
p=0
exit_status=0
for (( i=0; i<LEN; i++ )); do
    dname=${TESTDIRS[$i]}
    cd ${dname}
    echo "Running $dname ..."
    head README.md
    ./run_${dname}
    # Check exit status
    if [ $? -ne 0 ]; then
	echo -e "FAILED ${dname}\n"
	exit_status=1
    else
	echo -e "PASSED ${dname}\n"
	((p=p+1))
    fi
    cd ..
done

echo "#############################"
echo "PASSED $p out of ${LEN} tests"
echo "#############################"

# Format table for internal dev
if [ "${ARG}" = "cronicle" ];then
    read -r -d '' VAR << EOM
{
   "html": {
      "title": "Run results",
      "content": "<h1>Passed $p out of ${LEN} tests</h1>",
      "caption": "Run results, see below for any errors"
   }
}
EOM
echo $VAR
fi

exit $exit_status

