#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../shoc'
endif

echo "Testing 'z' model..."
rm -f in3.nc || true
rm -f out3_z.nc || true

$SHOC -g test3.prm in3.nc

$SHOC -p test3.prm

echo "DONE"

echo "Testing sigma model..."
rm -f in3.nc || true
rm -f out3_s.nc || true

$SHOC -g test3_s.prm in3.nc

$SHOC -p test3_s.prm

echo "DONE"

rm -f in3.nc || true
