#!/bin/csh -ef

# Set relative path to shoc executable
set SHOC='../../../hd/shoc'

echo "Testing 'z' model..."
rm -f in8.nc || true
rm -f out8_z.nc || true
rm -f out8_msl_z.nc || true

$SHOC -g test8.prm in8.nc

echo "Running, takes ~ 10 minutes...."
$SHOC -p test8.prm

echo "DONE"

echo "Running msl, takes ~ 10 minutes...."
$SHOC -p test8_msl.prm

echo "DONE"

rm -f in8.nc || true
