#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../../shoc'
endif

if (! $?COMPAS || "$COMPAS" == "") then
    set COMPAS='../../compas'
endif

echo "Testing SHOC..."
rm -f in1.nc
rm -f out1.nc

$SHOC -g test2.prm in1.nc

$SHOC -p test2.prm

echo "DONE"

echo "Testing COMPAS quad..."
rm -f in1_quad.nc
rm -f s_in1_quad.nc
rm -f out1_quad.nc

$COMPAS -g test2_quad.prm in1_quad.nc

$COMPAS -p test2_quad.prm

echo "DONE"

echo "Testing COMPAS quad 2 window..."
rm -f out1_quad2w.nc
rm -f win2.nc

$COMPAS -p test2_quad2w.prm

echo "DONE"

echo "Testing COMPAS hex..."
rm -f in1_hex.nc
rm -f out1_hex.nc

$COMPAS -g test2_hex.prm in1_hex.nc

$COMPAS -p test2_hex.prm

echo "DONE"

echo "Testing COMPAS hex 2 window..."
rm -f out1_hex2w.nc

$COMPAS -p test2_hex2w.prm

echo "DONE"
