/* config.h.  Generated by configure.  */
#if defined(_WIN32)
#define isnan _isnan
#define copysign _copysign
#define rint (int)
#define M_PI 3.14159265358979323846
#define TRILIBRARY
#define NO_TIMER
#elsif
#define ANSI_DECLARATORS
#endif

#define ANSI_DECLARATORS

#if defined(NO_COPYSIGN)
#define copysign(a, b) ((b >= 0.0) ? fabs(a) : -fabs(a))
#endif
