#!/bin/csh -f

echo "Testing SHOC..."
rm closed.nc
rm out1.nc

../shoc -g closed.prm closed.nc

../shoc -p closed.prm

echo "DONE"

echo "Testing COMPAS quad..."
rm closed_quad.nc
rm s_closed_quad.nc
rm out1_quad.nc
rm pt.nc

../compas -g closed_quad.prm closed_quad.nc

../compas -p closed_quad.prm

echo "DONE"

echo "Testing COMPAS quad 5 window..."
rm out1_quad5w.nc

../compas -p closed_quad5w.prm

echo "DONE"

echo "Testing COMPAS hex..."
rm closed_hex.nc
rm out1_hex.nc

../compas -g closed_hex.prm closed_hex.nc

../compas -p closed_hex.prm

echo "DONE"


