#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../shoc'
endif

if (! $?COMPAS || "$COMPAS" == "") then
    set COMPAS='../compas'
endif

echo "Testing SHOC..."
rm -f closed.nc
rm -f out1.nc

$SHOC -g closed.prm closed.nc

$SHOC -p closed.prm

echo "DONE"

echo "Testing COMPAS quad..."
rm -f closed_quad.nc
rm -f s_closed_quad.nc
rm -f out1_quad.nc
rm -f pt.nc

$COMPAS -g closed_quad.prm closed_quad.nc

$COMPAS -p closed_quad.prm

echo "DONE"

echo "Testing COMPAS quad 5 window..."
rm -f out1_quad5w.nc

$COMPAS -p closed_quad5w.prm

echo "DONE"

echo "Testing COMPAS hex..."
rm -f closed_hex.nc
rm -f out1_hex.nc

$COMPAS -g closed_hex.prm closed_hex.nc

$COMPAS -p closed_hex.prm

echo "DONE"
