#!/bin/bash

VERSION_TAG="$(docker image inspect  --format '{{ index .Config.Labels "org.opencontainers.image.version"}}' $IMAGE_NAME || true)"
if [ -n "${VERSION_TAG}" ]; then
    IMAGE_TAGGED="${DOCKER_REPO}:${VERSION_TAG}"
    docker tag $IMAGE_NAME $IMAGE_TAGGED
    docker push $IMAGE_TAGGED
fi
