#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../shoc'
endif

echo "Testing 'z' model..."
rm -f in6.nc || true
rm -f out6_z.nc || true

$SHOC -g test6.prm in6.nc

echo "Running, takes ~ 2 minutes...."
$SHOC -p test6.prm

echo "DONE"

rm -f in6.nc || true
