#!/bin/csh -ef

echo "Testing COMPAS cetas..."
rm -f *.msh
rm -f *.txt
rm -f *.us
rm -f *.jig
rm -f *.site
rm -f in.nc

if (! $?COMPAS || "$COMPAS" == "") then
    set COMPAS='../compas'
endif

$COMPAS -ag auto.prm

echo "DONE"
