#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../shoc'
endif

if (! $?COMPAS || "$COMPAS" == "") then
    set COMPAS='../compas'
endif


echo "Testing SHOC..."
rm -f est.nc
rm -f out1.nc

$SHOC -g est.prm est.nc

$SHOC -p est.prm

echo "DONE"

echo "Testing COMPAS quad..."
rm -f est_quad.nc
rm -f out1_quad.nc
rm -f s_est_quad.nc

$COMPAS -g est_quad.prm est_quad.nc

$COMPAS -p est_quad.prm

echo "DONE"

echo "Testing COMPAS quad 5 window..."
rm -f out1_quad5w.nc

$COMPAS -p est_quad5w.prm

echo "DONE"

echo "Testing COMPAS hex..."
rm -f est_hex.nc
rm -f out1_hex.nc

$COMPAS -g est_hex.prm est_hex.nc

$COMPAS -p est_hex.prm

echo "DONE"

echo "Testing COMPAS hex 5 window..."
rm -f out1_hex5w.nc

$COMPAS -p est_hex5w.prm

echo "DONE"
