#!/bin/csh -ef

if (! $?SHOC || "$SHOC" == "") then
    set SHOC='../shoc'
endif

echo "Testing 'z' model..."
rm -f in5.nc || true
rm -f out5_z.nc || true

$SHOC -g test5.prm in5.nc

echo "Running, takes ~ 30 sec...."
$SHOC -p test5.prm

echo "DONE"

echo "Testing sigma model..."
rm -f in5.nc || true
rm -f out5_s.nc || true

$SHOC -g test5_s.prm in5_s.nc

echo "Running, takes ~ 30 sec...."
$SHOC -p test5_s.prm

echo "DONE"

rm -f in5_s.nc || true
