/*
 *
 *  ENVIRONMENTAL MODELLING SUITE (EMS)
 *
 *  File: model/hd-us/tracers/autotracer.c
 *
 *  Description:
 *  Autotracer list.
 *  
 *  Copyright:
 *  Copyright (c) 2018. Commonwealth Scientific and Industrial
 *  Research Organisation (CSIRO). ABN 41 687 119 230. All rights
 *  reserved. See the license file for disclaimer and full
 *  use/redistribution conditions.
 *  
 *  $Id: load_tracer.c 7413 2023-10-05 02:10:10Z her127 $
 *
 */

#include <stdio.h>
#include <math.h>
#include "hd.h"
#include "tracer.h"

int NAUTOTR = 221;
tracer_info_t autotracerlist[] = {
  {
    .name = "salt",
    .long_name = "Salinity",
    .std_name = "sea_water_salinity",
    .units = "PSU",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 35.00,
    .type = WATER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .decay = "0.0",
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "temp",
    .long_name = "Temperature",
    .std_name = "sea_water_temperature",
    .units = "degrees C",
    .valid_range_wc[0] = -4.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 20.00,
    .type = WATER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .decay = "0.0",
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "u1mean",
    .long_name = "Mean 3D east velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC|E1VAR,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Mean 3D current",
    .vector_components = "u1mean u2mean",
    .groupkey = "vel3d_mean"
  },
  {
    .name = "u2mean",
    .long_name = "Mean 3D north velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC|E2VAR,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Mean 3D current",
    .vector_components = "u1mean u2mean",
    .groupkey = "vel3d_mean"
  },
  {
    .name = "wmean",
    .long_name = "Mean vertical velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vel3d_mean"
  },
  {
    .name = "temp_mean",
    .long_name = "Mean temperature",
    .units = "deg C",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ts_mean"
  },
  {
    .name = "salt_mean",
    .long_name = "Mean salinity",
    .units = "psu",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ts_mean"
  },
  {
    .name = "tracer_mean",
    .long_name = "Mean tracer",
    .units = "",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tra_mean"
  },
  {
    .name = "Kzmean",
    .long_name = "Mean Vertical Diffusivity",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "kz_mean"
  },
  {
    .name = "flux_e1",
    .long_name = "Advective flux through face",
    .units = "kgs-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "tr_flux"
  },
  {
    .name = "flux_e2",
    .long_name = "Advective flux through face",
    .units = "kgs-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "tr_flux"
  },
  {
    .name = "flux_w",
    .long_name = "Vertical advective flux",
    .units = "kgs-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "tr_flux"
  },
  {
    .name = "flux_kz",
    .long_name = "Vertical diffusive flux",
    .units = "kgs-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "tr_flux"
  },
  {
    .name = "regionid",
    .long_name = "Region identifier",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "regions"
  },
  {
    .name = "residence",
    .long_name = "Residence time",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "regions"
  },
  {
    .name = "flush",
    .long_name = "Flushing tracer",
    .units = "mgL-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 2.00e+00,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "flushing"
  },
  {
    .name = "age",
    .long_name = "Age tracer",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "age"
  },
  {
    .name = "percentile",
    .long_name = "Percentile for tracer",
    .units = "%",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "perc"
  },
  {
    .name = "tke",
    .long_name = "Turbulent Kinetic Energy",
    .units = "m2s-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PROGNOSTIC|CLOSURE,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "k-e k-w"
  },
  {
    .name = "diss",
    .long_name = "Dissipation",
    .units = "m2s-3",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PROGNOSTIC|CLOSURE,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "k-e"
  },
  {
    .name = "omega",
    .long_name = "Turbulence frequency",
    .units = "s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PROGNOSTIC|CLOSURE,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "k-w"
  },
  {
    .name = "tki",
    .long_name = "Turbulent Kinetic Intensity",
    .units = "m2s-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PROGNOSTIC|CLOSURE,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "my2.5 harcourt"
  },
  {
    .name = "tki_l",
    .long_name = "Turbulent Kinetic Intensity Length Scale",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PROGNOSTIC|CLOSURE,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "my2.5 harcourt"
  },
  {
    .name = "lscale",
    .long_name = "Turbulence length scale",
    .units = "metre",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.17,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "my2.5 harcourt my2.0"
  },
  {
    .name = "Kq",
    .long_name = "Turbulence mixing",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+00,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "my2.5 harcourt"
  },
  {
    .name = "smagorinsky",
    .long_name = "Smagorinsky diffusion",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "smag"
  },
  {
    .name = "layer_thick",
    .long_name = "Layer thickness",
    .units = "metre",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "rtemp",
    .long_name = "Relaxation temperature",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 5.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "rsalt",
    .long_name = "Relaxation salinity",
    .units = "psu",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "otemp",
    .long_name = "OFAM temperature",
    .units = "degrees C",
    .valid_range_wc[0] = -4.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ofam"
  },
  {
    .name = "osalt",
    .long_name = "OFAM salinity",
    .units = "psu",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ofam"
  },
  {
    .name = "temp_tc",
    .long_name = "Relaxation temperature time constant",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "salt_tc",
    .long_name = "Relaxation salinity time constant",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "smag"
  },
  {
    .name = "ovelu",
    .long_name = "OFAM east velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Global 3D current",
    .vector_components = "ovelu ovelv",
    .groupkey = "NONE"
  },
  {
    .name = "ovelv",
    .long_name = "OFAM north velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Global 3D current",
    .vector_components = "ovelu ovelv",
    .groupkey = "NONE"
  },
  {
    .name = "mom_balance",
    .long_name = "Momentum balance maximum",
    .units = "%",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tend"
  },
  {
    .name = "u1_adv",
    .long_name = "East advective tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Advective current",
    .vector_components = "u1_adv u2_adv",
    .groupkey = "tend"
  },
  {
    .name = "u1_hdif",
    .long_name = "East horizontal diffusion tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Hdiffusion current",
    .vector_components = "u1_hdif u2_hdif",
    .groupkey = "tend"
  },
  {
    .name = "u1_vdif",
    .long_name = "East vertical diffusion tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Vdiffusion current",
    .vector_components = "u1_vdif u2_vdif",
    .groupkey = "tend"
  },
  {
    .name = "u1_btp",
    .long_name = "East barotropic pressure gradient tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Barotropic current",
    .vector_components = "u1_btp u2_btp",
    .groupkey = "tend"
  },
  {
    .name = "u1_cor",
    .long_name = "East Coriolis tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Coriolis surrent",
    .vector_components = "u1_cor u2_cor",
    .groupkey = "tend"
  },
  {
    .name = "u1_sto",
    .long_name = "East Stokes tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Stokes current",
    .vector_components = "u1_sto u2_sto",
    .groupkey = "tend_wave"
  },
  {
    .name = "u2_adv",
    .long_name = "North advective tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Advective current",
    .vector_components = "u1_adv u2_adv",
    .groupkey = "tend"
  },
  {
    .name = "u2_hdif",
    .long_name = "North horizontal diffusion tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Hdiffusion current",
    .vector_components = "u1_hdif u2_hdif",
    .groupkey = "tend"
  },
  {
    .name = "u2_vdif",
    .long_name = "North vertical diffusion tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Vdiffusion current",
    .vector_components = "u1_vdif u2_vdif",
    .groupkey = "tend"
  },
  {
    .name = "u2_btp",
    .long_name = "North barotropic pressure gradient tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Barotropic current",
    .vector_components = "u1_btp u2_btp",
    .groupkey = "tend"
  },
  {
    .name = "u2_cor",
    .long_name = "North Coriolis tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Coriolis surrent",
    .vector_components = "u1_cor u2_cor",
    .groupkey = "tend"
  },
  {
    .name = "u2_sto",
    .long_name = "North Stokes tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Stokes current",
    .vector_components = "u1_sto u2_sto",
    .groupkey = "tend_wave"
  },
  {
    .name = "tra_adv",
    .long_name = "Tracer advective tendency",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tr_tend"
  },
  {
    .name = "tra_vdif",
    .long_name = "Tracer vertical diffusive tendency",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tr_tend"
  },
  {
    .name = "tra_ncon",
    .long_name = "Tracer non-conservative tendency",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tr_tend"
  },
  {
    .name = "wave_stke1",
    .long_name = "Stokes sub-surface velocity along e1",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "spec_wave"
  },
  {
    .name = "wave_stke2",
    .long_name = "Stokes sub-surface velocity along e2",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "spec_wave"
  },
  {
    .name = "brunt_vaisala",
    .long_name = "Brunt Vaisala Frequency",
    .units = "s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "int_wave_speed",
    .long_name = "Internal wave speed",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "richardson_gr",
    .long_name = "Gradient Richardson number",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "richardson_fl",
    .long_name = "Flux Richardson number",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "reynolds",
    .long_name = "Reynolds number",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "froude",
    .long_name = "Froude number",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "sigma_t",
    .long_name = "Sigma_t",
    .units = "kgm-3",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "energy",
    .long_name = "Mechanical energy",
    .units = "Jm-3",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "kenergy",
    .long_name = "Kinetic energy",
    .units = "Jm-3",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "ptconc",
    .long_name = "Particle concentration",
    .units = "kgm-3",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "sound",
    .long_name = "Speed of sound",
    .units = "ms-1",
    .valid_range_wc[0] = 1.00e+03,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "sound"
  },
  {
    .name = "sound_channel",
    .long_name = "Sound channel depth",
    .units = "m",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "sound"
  },
  {
    .name = "rossby_internal",
    .long_name = "Internal Rossby radius",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "current_speed_3d",
    .long_name = "Current Speed 3D",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "shear_vert",
    .long_name = "Vertical velocity shear",
    .units = "s-1",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "buoy_prod",
    .long_name = "Buoyancy production",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "shear_prod",
    .long_name = "Shear production",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "decorr_e1",
    .long_name = "Decorrelation length scale",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "imp3dn",
    .long_name = "imp3dn",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "tracer1",
    .long_name = "Dummy tracer 1",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "dummies"
  },
  {
    .name = "tracer2",
    .long_name = "Dummy tracer 2",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "dummies"
  },
  {
    .name = "tracer3",
    .long_name = "Dummy tracer 3",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "dummies"
  },
  {
    .name = "unit",
    .long_name = "Unit tracer",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 1.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "passive",
    .long_name = "Passive tracer",
    .units = "kgm-3",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 1,
    .diffuse = 1,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "glider",
    .long_name = "Glider density",
    .units = "kgm-3",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "u1vhc",
    .long_name = "Horizontal viscosity cell centered",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "vol_cont",
    .long_name = "Volume continuity",
    .units = "m3",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "cell_index",
    .long_name = "Cell centre index",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "nprof",
    .long_name = "Normalized  vertical profile",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "mono",
    .long_name = "Monotinicity",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "reef_fraction_e1",
    .long_name = "Fraction of reef in cell e1 direction",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "porusplate"
  },
  {
    .name = "reef_fraction_e2",
    .long_name = "Fraction of reef in cell e2 direction",
    .units = "",
    .valid_range_wc[0] = -1.00e+35,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "porusplate"
  },
  {
    .name = "flow_salt",
    .long_name = "River flow salinity",
    .units = "psu",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+35,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 1,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "swr_attenuation",
    .long_name = "SWR attenuation",
    .units = "m-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "cfl2d",
    .long_name = "2D CFL timestep",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "cfl3d",
    .long_name = "3D CFL timestep",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "courant",
    .long_name = "Courant timestep",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "lipschitz",
    .long_name = "Lipschitz timestep",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "diffstab",
    .long_name = "Horizontal diffusion timestep",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "courant_no",
    .long_name = "Courant Number",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "cfl"
  },
  {
    .name = "mixed_layer",
    .long_name = "Mixed layer depth",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "steric",
    .long_name = "Steric height",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "abs_vor",
    .long_name = "Absolute vorticity",
    .units = "s-1",
    .valid_range_wc[0] = 1.10e+05,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "rel_vor",
    .long_name = "Relative vorticity",
    .units = "s-1",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "pot_vor",
    .long_name = "Potential vorticity",
    .units = "m-1s-1",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "rv_drvdt",
    .long_name = "RV rate of change tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_nonlin",
    .long_name = "RV nonlinear tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_beta",
    .long_name = "RV planetary vorticity tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_strch",
    .long_name = "RV topographic vorticity tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_jebar",
    .long_name = "RV JEBAR tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_wsc",
    .long_name = "RV wind stress curl tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "rv_bsc",
    .long_name = "RV bottom stress curl tendency",
    .units = "s-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "vorticity"
  },
  {
    .name = "u1vh_region",
    .long_name = "Regions for viscosity",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "rossby_external",
    .long_name = "External Rossby radius",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "current_speed_2d",
    .long_name = "Current Speed 2D",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+11,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "obc_phase",
    .long_name = "OBC phase speed",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "wind_Cd",
    .long_name = "Momentum drag coefficient",
    .units = "",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "cell_resolution",
    .long_name = "Mean Cell Resolution",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "resolution"
  },
  {
    .name = "cell_area_sqrt",
    .long_name = "sqrt(cell area)",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "resolution"
  },
  {
    .name = "edge_area_sqrt",
    .long_name = "sqrt(edge area)",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "resolution"
  },
  {
    .name = "cell_area",
    .long_name = "Cell area",
    .units = "m^2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "area"
  },
  {
    .name = "edge_area",
    .long_name = "Mean edge area",
    .units = "m^2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "area"
  },
  {
    .name = "mesh_uniformity",
    .long_name = "Mesh uniformity index",
    .units = "%",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "u1_rad",
    .long_name = "u1 radiation stress tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "rad_stress"
  },
  {
    .name = "u2_rad",
    .long_name = "u2 radiation stress tendency",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "rad_stress"
  },
  {
    .name = "eta_mean",
    .long_name = "Mean elevation",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "w1mean",
    .long_name = "Mean eastward wind stress",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wind_mean"
  },
  {
    .name = "w2mean",
    .long_name = "Mean northward wind stress",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wind_mean"
  },
  {
    .name = "u1av_mean",
    .long_name = "Mean 2D east velocity ",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Mean 2D current",
    .vector_components = "u1av_mean u2av_mean",
    .groupkey = "vel2d_mean"
  },
  {
    .name = "u2av_mean",
    .long_name = "Mean 2D north velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Mean 2D current",
    .vector_components = "u1av_mean u2av_mean",
    .groupkey = "vel2d_mean"
  },
  {
    .name = "tracer_mean_2d",
    .long_name = "tracer_mean_2d",
    .units = "",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "nhf",
    .long_name = "Net heat flux",
    .units = "W m-2",
    .valid_range_wc[0] = -1.00e+03,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "heatflux netheat"
  },
  {
    .name = "swr",
    .long_name = "Short wave radiation",
    .units = "W m-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "heatflux heatcomp netheat"
  },
  {
    .name = "lwr",
    .long_name = "Long wave radiation",
    .units = "W m-2",
    .valid_range_wc[0] = -1.00e+03,
    .valid_range_wc[1] = 1.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "heatflux heatcomp"
  },
  {
    .name = "lhf",
    .long_name = "Latent heat flux",
    .units = "W m-2",
    .valid_range_wc[0] = -1.00e+03,
    .valid_range_wc[1] = 1.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "heatflux heatcomp"
  },
  {
    .name = "shf",
    .long_name = "Sensible heat flux",
    .units = "W m-2",
    .valid_range_wc[0] = -1.00e+03,
    .valid_range_wc[1] = 1.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "heatflux heatcomp"
  },
  {
    .name = "precip",
    .long_name = "Precipitation rate",
    .units = "ms-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "saltflux"
  },
  {
    .name = "evap",
    .long_name = "Evaporation rate",
    .units = "ms-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "saltflux"
  },
  {
    .name = "nsf",
    .long_name = "Net salt flux",
    .units = "ms-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 2.00e+03,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "wave_Cd",
    .long_name = "Wave enhanced bottom drag",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "wave_Sxy",
    .long_name = "Radiation stress, x tangential",
    .units = "m2s-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "rad_force"
  },
  {
    .name = "wave_Syx",
    .long_name = "Radiation stress, y tangential",
    .units = "m2s-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "rad_force"
  },
  {
    .name = "wave_Fx",
    .long_name = "Wave-induced force x direction",
    .units = "Nm-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_force"
  },
  {
    .name = "wave_Fy",
    .long_name = "Wave-induced force y direction",
    .units = "Nm-2",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_force"
  },
  {
    .name = "wave_ste1",
    .long_name = "Stokes velocity x direction",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stokes"
  },
  {
    .name = "wave_ste2",
    .long_name = "Stokes velocity y direction",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stokes"
  },
  {
    .name = "tau_w1",
    .long_name = "Wave supported wind stress x direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stress"
  },
  {
    .name = "tau_w2",
    .long_name = "Wave supported wind stress y direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stress"
  },
  {
    .name = "tau_diss1",
    .long_name = "Wave to ocean stress x direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stress"
  },
  {
    .name = "tau_diss2",
    .long_name = "Wave to ocean stress y direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_stress"
  },
  {
    .name = "wave_Kb",
    .long_name = "Low order Bernoulli head",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_k",
    .long_name = "Wavenumber",
    .units = "m-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.01,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "wave_P",
    .long_name = "Wave-averaged sea state",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|FORCING,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "ustrcw",
    .long_name = "Wave current friction",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "waves"
  },
  {
    .name = "wave_ub",
    .long_name = "Wave orbital velocity",
    .units = "ms-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "waves"
  },
  {
    .name = "wave_period",
    .long_name = "Wave period",
    .units = "s",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 10.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "waves"
  },
  {
    .name = "wave_dir",
    .long_name = "Wave direction",
    .units = "deg",
    .valid_range_wc[0] = -3.60e+02,
    .valid_range_wc[1] = 3.60e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "waves"
  },
  {
    .name = "wave_amp",
    .long_name = "Wave amplitude",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "waves"
  },
  {
    .name = "wave_fwcapx",
    .long_name = "Wave whitecapping, x direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fbrex",
    .long_name = "Wave depth-induced breaking, x direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fbotx",
    .long_name = "Wave bottom friction dissipation, x direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fsurx",
    .long_name = "Wave surface streaming, x direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_wfdx",
    .long_name = "Wave form drag, x direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_wovsx",
    .long_name = "Wave ocean viscous stress, x direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_frolx",
    .long_name = "Wave roller, x direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fwcapy",
    .long_name = "Wave whitecapping, y direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fbrey",
    .long_name = "Wave depth-induced breaking, y direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fboty",
    .long_name = "Wave bottom friction dissipation, y direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_fsury",
    .long_name = "Wave surface streaming, y direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_wfdy",
    .long_name = "Wave form drag, y direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_wovsy",
    .long_name = "Wave ocean viscous stress, y direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "wave_froly",
    .long_name = "Wave roller, y direction",
    .units = "m2s-2",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|WAVE|PROGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wave_nearshore"
  },
  {
    .name = "oeta",
    .long_name = "Relaxation elevation",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "eta_tc",
    .long_name = "Relaxation eta time constant",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "AVHRR",
    .long_name = "AVHRR SST",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .reset_file = "avhrr_list.txt(AVHRR=sst)",
    .reset_dt = "1 day",
    .groupkey = "NONE"
  },
  {
    .name = "ghrsst",
    .long_name = "GHRSST L4 SST",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ghrsst"
  },
  {
    .name = "ghrsst_error",
    .long_name = "ghrsst_error",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ghrsst"
  },
  {
    .name = "windows",
    .long_name = "window partitions",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "windiag"
  },
  {
    .name = "windex",
    .long_name = "window indexing",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "windiag"
  },
  {
    .name = "bathy_range_min",
    .long_name = "Bathymetry deviation above",
    .units = "m",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "bathystat"
  },
  {
    .name = "bathy_range_max",
    .long_name = "Bathymetry deviation below",
    .units = "m",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "bathystat"
  },
  {
    .name = "bathy_grad",
    .long_name = "Bathymetry gradient",
    .units = "",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "bathystat"
  },
  {
    .name = "bathy_grad_max",
    .long_name = "Bathymetry maximum gradient deviation",
    .units = "",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "bathystat"
  },
  {
    .name = "alerts_actual",
    .long_name = "alerts; actual",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "alerts"
  },
  {
    .name = "alerts_cumulative",
    .long_name = "alerts; cumulative",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+34,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "alerts"
  },
  {
    .name = "U1VH0",
    .long_name = "Initial e1 horizontal viscosity",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+34,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "alerts"
  },
  {
    .name = "U2VH0",
    .long_name = "Initial e1 horizontal viscosity",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+34,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "alerts"
  },
  {
    .name = "vol_cons",
    .long_name = "Volume conservation",
    .units = "%",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "sonic_depth",
    .long_name = "Sonic depth",
    .units = "m",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "sound2d"
  },
  {
    .name = "sep",
    .long_name = "Surface Ekman pumping",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ekman"
  },
  {
    .name = "bep",
    .long_name = "Bottom Ekman pumping",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "ekman"
  },
  {
    .name = "SH_tide_front",
    .long_name = "Simpson-Hunter index",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "wind_speed",
    .long_name = "Wind speed",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wind"
  },
  {
    .name = "wind_dir",
    .long_name = "Wind direction",
    .units = "degT",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "wind"
  },
  {
    .name = "wet_cells",
    .long_name = "Wet cell diagnostic",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "surf_layer",
    .long_name = "k index of surface layer",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "surf_slope",
    .long_name = "Mean surface slope",
    .units = "m/m",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "tau_be1",
    .long_name = "Bottom stress in north direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Bottom stress",
    .vector_components = "tau_be1 tau_be2",
    .groupkey = "botstress"
  },
  {
    .name = "tau_be2",
    .long_name = "Bottom stress in north direction",
    .units = "Nm-2",
    .valid_range_wc[0] = -1.00e+04,
    .valid_range_wc[1] = 1.00e+04,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Bottom stress",
    .vector_components = "tau_be1 tau_be2",
    .groupkey = "botstress"
  },
  {
    .name = "swr_bot_absorb",
    .long_name = "SWR bottom absorption",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+00,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "botstress"
  },
  {
    .name = "swr_attenuation",
    .long_name = "SWR attenuation",
    .units = "m-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "botstress"
  },
  {
    .name = "swr_deep_attenuation",
    .long_name = "SWR deep attenuation",
    .units = "m-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "swr_transmission",
    .long_name = "SWR transmission",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+00,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "swreg",
    .long_name = "SWR param estimation RMSE",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "swr_regions"
  },
  {
    .name = "swrms",
    .long_name = "SWR param estimation RMSE",
    .units = "degrees C",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "swr_regions"
  },
  {
    .name = "attn_mean",
    .long_name = "SWR mean attenuation",
    .units = "m-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "swr_regions"
  },
  {
    .name = "tran_mean",
    .long_name = "SWR mean transmission",
    .units = "",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+00,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|PARAMETER,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "swr_regions"
  },
  {
    .name = "flow",
    .long_name = "River flow",
    .units = "m3s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "flow_depth",
    .long_name = "River flow depth",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "equitide",
    .long_name = "Equilibrium tide",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "tpxotide",
    .long_name = "TPXO tide",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "tpxou",
    .long_name = "TPXO x velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tpxo_vel"
  },
  {
    .name = "tpxov",
    .long_name = "TPXO y velocity",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tpxo_vel"
  },
  {
    .name = "tpxoU",
    .long_name = "TPXO x transport",
    .units = "m2s-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tpxo_tran"
  },
  {
    .name = "tpxoV",
    .long_name = "TPXO y transport",
    .units = "m2s-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "tpxo_tran"
  },
  {
    .name = "UAT",
    .long_name = "Eastward 2D transport",
    .units = "m2s-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "transport_2d"
  },
  {
    .name = "VAT",
    .long_name = "Northward 2D transport",
    .units = "m2s-1",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "transport_2d"
  },
  {
    .name = "decorr_e1",
    .long_name = "Decorrelation length scale",
    .units = "m",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "imp2dn",
    .long_name = "imp2dn",
    .units = "",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "eta_tc",
    .long_name = "Relaxation eta time constant",
    .units = "days",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "eta_relax"
  },
  {
    .name = "eta_inc",
    .long_name = "Relaxation eta increment",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "eta_relax"
  },
  {
    .name = "eta_force",
    .long_name = "Eta forcing",
    .units = "m",
    .valid_range_wc[0] = -1.00e+10,
    .valid_range_wc[1] = 1.00e+10,
    .fill_value_wc = 0.00,
    .type = INTER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "FORCE2D"
  },
  {
    .name = "temp_force",
    .long_name = "Temperature forcing",
    .units = "degrees C",
    .valid_range_wc[0] = -4.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "FORCE3D"
  },
  {
    .name = "salt_force",
    .long_name = "Salinity forcing",
    .units = "psu",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 4.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "FORCE3D"
  },
  {
    .name = "velu_force",
    .long_name = "East velocity forcing",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Forcing 3D current",
    .vector_components = "velu_force velv_force",
    .groupkey = "FORCE3D"
  },
  {
    .name = "velv_force",
    .long_name = "North velocity forcing",
    .units = "ms-1",
    .valid_range_wc[0] = -1.00e+02,
    .valid_range_wc[1] = 1.00e+02,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .vector_name = "Forcing 3D current",
    .vector_components = "velu_force velv_force",
    .groupkey = "FORCE3D"
  },
  {
    .name = "VZ0",
    .long_name = "Background vertical viscosity",
    .units = "m2s-1",
    .valid_range_wc[0] = 1.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  },
  {
    .name = "KZ0",
    .long_name = "Background vertical diffusivity",
    .units = "m2s-1",
    .valid_range_wc[0] = 0.00e+00,
    .valid_range_wc[1] = 1.00e+01,
    .fill_value_wc = 0.00,
    .type = WATER|HYDRO|DIAGNOSTIC,
    .inwc = 1,
    .dissol = 1,
    .advect = 0,
    .diffuse = 0,
    .diagn = 0,
    .m = -1,
    .groupkey = "NONE"
  }
};
